interface abilitydatatype{
  [key:string]:{
    name?:string,
    icon?:string,
    method?:string,
    range?:number,
    area?:number,
    cool?:number,
    cost?:number,
    action?:string,
    targettp?:string,
    cast?:number,
    type?:string,
  }
}
const abilitydata:abilitydatatype={
  "abil_1":{
    name:"abil_1",
    icon:"ReplaceableTextures\\CommandButtons\\BTNBreathOfFrost.blp",
    method:"点",
    range:500,
    area:500,
    cool:0,
    cost:1,
    action:"",
    targettp:"敌人",
    cast:1,
    type:"",
  },
  "abil_2":{
    name:"abil_2",
    icon:"ReplaceableTextures\\CommandButtons\\BTNBreathOfFrost.blp",
    method:"点",
    range:500,
    area:500,
    cool:0,
    cost:1,
    action:"",
    targettp:"敌人",
    cast:1,
    type:"",
  },
}
