//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	name = 名字
	describe = 提示说明
	kind = 种类
	dur = 持续时间
	interval = 间隔
	levelMax = 叠加层数上限
	attribute = buff附加属性
	priority = 优先级
	isDebuff = 是否Debuff
	levelDurMode = 每层buff独立计时
	icon = 图标
	modelAttachTarget = 目标附加点
	model = 目标附加模型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	describe?: string
	kind?: any
	dur?: number
	interval?: any
	levelMax?: any
	attribute?: any
	priority?: any
	isDebuff?: boolean
	levelDurMode?: boolean
	icon?: string
	modelAttachTarget?: string
	model?: string
    [key:string]: any
}

declare global {
    type t_基础演员buff = data_type
}

export const data: data_type[] = [
	{
		"id":"眩晕",
		"class":"基础",
		"name":"眩晕",
		"describe":"眩晕",
		"dur":5,
		"isDebuff":true,
		"levelDurMode":true,
		"icon":"ReplaceableTextures\\CommandButtons\\BTNStun.blp",
		"modelAttachTarget":"overhead",
		"model":"Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl"
	}
]
export const d_基础演员buff = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
