//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	name = 名字
	describe = 提示说明
	templateType = 基础模板
	strength = 基础力量
	agility = 基础敏捷
	intelligence = 基础智力
	attribute = 属性
	icon = 图标
	model = 模型
	moveSpeed = 移速
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	sellItems = (内置有效)售卖演员物品类型id列表
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	describe?: string
	templateType?: string
	strength?: number
	agility?: number
	intelligence?: number
	attribute?: any
	icon?: any
	model?: any
	moveSpeed?: any
	maxLife?: number
	maxMana?: number
	def?: any
	damage?: any
	damageCd?: any
	range?: any
	missileModel?: any
	moveType?: any
	flyHeight?: any
	goldCost?: any
	sellItems?: any
    [key:string]: any
}

declare global {
    type t_基础单位演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"测试英雄",
		"class":"基础单位",
		"name":"测试英雄",
		"describe":"测试英雄",
		"templateType":"近战力量英雄",
		"strength":50,
		"agility":50,
		"intelligence":50,
		"attribute":{
			"strength_p":3,
			"attack_p":5
		},
		"maxLife":10000,
		"maxMana":10000
	}
]
export const d_基础单位演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
