globals
//globals from YDTriggerSaveLoadSystem:
constant boolean LIBRARY_YDTriggerSaveLoadSystem=true
hashtable YDHT
hashtable YDLOC
//endglobals from YDTriggerSaveLoadSystem
//globals from YDWEGetUnitsInRectMatchingNull:
constant boolean LIBRARY_YDWEGetUnitsInRectMatchingNull=true
group yd_NullTempGroup
//endglobals from YDWEGetUnitsInRectMatchingNull
//globals from YDWETriggerRegisterEnterRectSimpleNull:
constant boolean LIBRARY_YDWETriggerRegisterEnterRectSimpleNull=true
region yd_NullTempRegion
//endglobals from YDWETriggerRegisterEnterRectSimpleNull
    // User-defined
integer array udg_G_UT
timer udg_G_Timer= null
timerdialog udg_G_TimerFace= null
integer udg_G_Class= 0
group udg_G_Group= null
unit array udg_Heros
force udg_Player= null
rect array udg_S_jux
integer array udg_S_wplx
integer array udg_S_ut
    // Generated
rect gg_rct______________000= null
rect gg_rct______________001= null
rect gg_rct______________002= null
rect gg_rct______________003= null
rect gg_rct______________004= null
rect gg_rct______________005= null
rect gg_rct______________006________2= null
rect gg_rct______________009= null
rect gg_rct______________010= null
rect gg_rct______________010_______u= null
trigger gg_trg__________u= null
trigger gg_trg_SetDate= null
trigger gg_trg_hg= null
trigger gg_trg_G_Action= null
trigger gg_trg_G_allattack_1= null
trigger gg_trg_G_allattack_2= null
trigger gg_trg_G_victory= null
trigger gg_trg_Choosehero= null
trigger gg_trg_RegetHero= null
trigger gg_trg_s1= null
trigger gg_trg_s2= null
trigger gg_trg_s3= null
trigger gg_trg_Chooseclass= null
unit gg_unit_n000_0024= null

trigger l__library_init

//JASSHelper struct globals:

endglobals


//library YDTriggerSaveLoadSystem:
    function YDTriggerSaveLoadSystem___Init takes nothing returns nothing
            set YDHT=InitHashtable()
        set YDLOC=InitHashtable()
    endfunction

//library YDTriggerSaveLoadSystem ends
//library YDWEGetUnitsInRectMatchingNull:
function YDWEGetUnitsInRectMatchingNull takes rect r,boolexpr filter returns group
    local group g= CreateGroup()
    call GroupEnumUnitsInRect(g, r, filter)
    call DestroyBoolExpr(filter)
    set yd_NullTempGroup=g
    set g=null
    return yd_NullTempGroup
endfunction

//library YDWEGetUnitsInRectMatchingNull ends
//library YDWETriggerRegisterEnterRectSimpleNull:
function YDWETriggerRegisterEnterRectSimpleNull takes trigger trig,rect r returns event
    local region rectRegion= CreateRegion()
    call RegionAddRect(rectRegion, r)
    set yd_NullTempRegion=rectRegion
    set rectRegion=null
    return TriggerRegisterEnterRegion(trig, yd_NullTempRegion, null)
endfunction

//library YDWETriggerRegisterEnterRectSimpleNull ends
//===========================================================================
// 
// 防守图模版
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Thu Jan 18 12:48:43 2018
//   Map Author: 指天求虐
// 
//===========================================================================
//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************
function InitGlobals takes nothing returns nothing
    local integer i= 0
    set udg_G_Timer=CreateTimer()
    set udg_G_Class=0
    set udg_G_Group=CreateGroup()
    set udg_Player=CreateForce()
endfunction
//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************
//===========================================================================
function CreateBuildingsForPlayer4 takes nothing returns nothing
    local player p= Player(4)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set u=CreateUnit(p, 'hcas', - 1536.0, - 3072.0, 270.000)
    set u=CreateUnit(p, 'hgtw', - 1984.0, - 2304.0, 270.000)
    set u=CreateUnit(p, 'hgtw', - 1088.0, - 2304.0, 270.000)
endfunction
//===========================================================================
function CreateUnitsForPlayer4 takes nothing returns nothing
    local player p= Player(4)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set u=CreateUnit(p, 'ushd', - 1092.1, 2720.1, 150.803)
endfunction
//===========================================================================
function CreateUnitsForPlayer5 takes nothing returns nothing
    local player p= Player(5)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set gg_unit_n000_0024=CreateUnit(p, 'n000', - 2672.8, - 2566.6, 356.930)
endfunction
//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p= Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set u=CreateUnit(p, 'ngme', - 448.0, - 2752.0, 270.000)
    set u=CreateUnit(p, 'nfoh', - 2688.0, - 2560.0, 270.000)
    set u=CreateUnit(p, 'nmoo', - 2688.0, - 3072.0, 270.000)
endfunction
//===========================================================================
function CreateNeutralPassive takes nothing returns nothing
    local player p= Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set u=CreateUnit(p, 'Hpal', - 1807.1, 2963.4, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Hamg', - 1680.8, 2964.6, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Hmkg', - 1547.7, 2958.8, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Hblm', - 1414.1, 2971.4, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Obla', - 1807.5, 2790.8, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Ofar', - 1671.9, 2802.6, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Otch', - 1525.8, 2807.9, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Oshd', - 1384.5, 2802.7, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Ekee', - 1816.7, 2637.3, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Emoo', - 1668.9, 2633.6, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Edem', - 1531.3, 2618.0, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Ewar', - 1392.0, 2669.6, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Udea', - 1825.7, 2538.1, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Ulic', - 1683.1, 2489.8, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Udre', - 1531.5, 2520.2, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
    set u=CreateUnit(p, 'Ucrl', - 1375.9, 2467.7, 270.000)
    call SetUnitState(u, UNIT_STATE_MANA, 0)
    call UnitAddItemToSlotById(u, 'ratf', 0)
endfunction
//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer4()
endfunction
//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer4()
    call CreateUnitsForPlayer5()
endfunction
//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings()
    call CreateBuildingsForPlayer4() // INLINED!!
    call CreateNeutralPassive()
    call CreatePlayerUnits()
endfunction
//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************
function CreateRegions takes nothing returns nothing
    local weathereffect we
    set gg_rct______________000=Rect(- 1696.0, - 2944.0, - 1408.0, - 2752.0)
    set gg_rct______________001=Rect(1792.0, 1536.0, 2784.0, 2528.0)
    set gg_rct______________002=Rect(1792.0, - 352.0, 2784.0, 608.0)
    set gg_rct______________003=Rect(1792.0, - 2272.0, 2784.0, - 1312.0)
    set gg_rct______________004=Rect(- 96.0, 2784.0, 96.0, 2976.0)
    set gg_rct______________005=Rect(- 3168.0, 2752.0, - 2976.0, 2944.0)
    set gg_rct______________006________2=Rect(- 1632.0, 704.0, - 1504.0, 832.0)
    set gg_rct______________009=Rect(- 1664.0, 2624.0, - 1536.0, 2752.0)
    set gg_rct______________010=Rect(- 2080.0, 736.0, - 1952.0, 864.0)
    set gg_rct______________010_______u=Rect(- 1152.0, 736.0, - 1024.0, 864.0)
endfunction
//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************
//===========================================================================
// Trigger: 初始化
//===========================================================================
function Trig__________uActions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call QuestMessageBJ(GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, "双击选英雄。")
    call CameraSetSmoothingFactor(1.20)
    call CreateFogModifierRectBJ(true, Player(4), FOG_OF_WAR_VISIBLE, GetPlayableMapRect())
    call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRectCenter(gg_rct______________009))
    set bj_forLoopAIndex=1
    set bj_forLoopAIndexEnd=4
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        call PanCameraToTimedLocForPlayer(ConvertedPlayer(bj_forLoopAIndex), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8), 0)
        set bj_forLoopAIndex=bj_forLoopAIndex + 1
    endloop
    call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call ConditionalTriggerExecute(gg_trg_SetDate)
    call TriggerSleepAction(5.00)
    call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    set udg_G_Class=1
    call StartTimerBJ(udg_G_Timer, false, 30)
    call CreateTimerDialogBJ(GetLastCreatedTimerBJ(), ( "第" + ( I2S(udg_G_Class) + "即将来临" ) ))
    set udg_G_TimerFace=GetLastCreatedTimerDialogBJ()
    call DestroyTrigger(GetTriggeringTrigger())
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig__________u takes nothing returns nothing
    set gg_trg__________u=CreateTrigger()
    call TriggerAddAction(gg_trg__________u, function Trig__________uActions)
endfunction
//===========================================================================
// Trigger: SetDate
//===========================================================================
function Trig_SetDateActions takes nothing returns nothing
    local integer i=0
    // 刷怪变量
    set i=i + 1
    set udg_G_UT[i]='hfoo'
    set i=i + 1
    set udg_G_UT[i]='hrif'
    set i=i + 1
    set udg_G_UT[i]='hkni'
    set i=i + 1
    set udg_G_UT[i]='hspt'
    set i=i + 1
    set udg_G_UT[i]='orai'
    set i=i + 1
    set udg_G_UT[i]='otau'
    set i=i + 1
    set udg_G_UT[i]='okod'
    set i=i + 1
    set udg_G_UT[i]='uabo'
    set i=i + 1
    set udg_G_UT[i]='nstl'
    set i=i + 1
    set udg_G_UT[i]='nwld'
    set i=i + 1
    set udg_G_UT[i]='nstw'
    // 练功房
    // 刷金币
    set udg_S_jux[1]=gg_rct______________001
    set udg_S_ut[1]='h002'
    set udg_S_wplx[1]='I000'
    // 刷木头
    set udg_S_jux[2]=gg_rct______________002
    set udg_S_ut[2]='h003'
    set udg_S_wplx[2]='I001'
    // 刷属性
    set udg_S_jux[3]=gg_rct______________003
    set udg_S_ut[3]='h004'
    set udg_S_wplx[3]='I002'
    // 排泄
    call DestroyTrigger(GetTriggeringTrigger())
endfunction
//===========================================================================
function InitTrig_SetDate takes nothing returns nothing
    set gg_trg_SetDate=CreateTrigger()
    call TriggerAddAction(gg_trg_SetDate, function Trig_SetDateActions)
endfunction
//===========================================================================
// Trigger: hg
//===========================================================================
function Trig_hgActions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRectCenter(gg_rct______________000))
    call SetUnitPositionLoc(udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())], LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call PanCameraToTimedLocForPlayer(GetOwningPlayer(udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())]), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8), 0)
    call SelectUnitForPlayerSingle(udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())], GetOwningPlayer(udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())]))
    call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_hg takes nothing returns nothing
    set gg_trg_hg=CreateTrigger()

        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(0), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(1), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(2), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(3), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(4), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(5), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(6), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(7), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(8), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(9), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(10), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(11), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(12), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(13), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(14), "hg", true)
        call TriggerRegisterPlayerChatEvent(gg_trg_hg, Player(15), "hg", true)
    call TriggerAddAction(gg_trg_hg, function Trig_hgActions)
endfunction
//===========================================================================
// Trigger: G_Action
//===========================================================================
function Trig_G_ActionActions takes nothing returns nothing
    local integer ydul_t
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call DestroyTimerDialog(udg_G_TimerFace)
    // 每次怪数量比上次多2个
    set ydul_t=1
    loop
        exitwhen ydul_t > ( ( 10 ) + ( ( ( 2 ) * ( udg_G_Class ) ) ) )
        call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x50525CFC, GetRectCenter(gg_rct______________005))
        call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0xDEFC4000, GetRectCenter(gg_rct______________004))
        call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x31706F5A, GetRectCenter(gg_rct______________010))
        call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x9A060300, GetRectCenter(gg_rct______________010_______u))
        // 创建
        call CreateNUnitsAtLoc(1, udg_G_UT[udg_G_Class], Player(5), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x50525CFC), bj_UNIT_FACING)
        call AddSpecialEffectLocBJ(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x50525CFC), "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.mdl")
        call DestroyEffect(GetLastCreatedEffectBJ())
        call RemoveGuardPosition(GetLastCreatedUnit())
        call GroupAddUnitSimple(GetLastCreatedUnit(), udg_G_Group)
        call IssuePointOrderLoc(GetLastCreatedUnit(), "attack", LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x31706F5A))
        // 创建
        call CreateNUnitsAtLoc(1, udg_G_UT[udg_G_Class], Player(5), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0xDEFC4000), bj_UNIT_FACING)
        call AddSpecialEffectLocBJ(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0xDEFC4000), "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.mdl")
        call DestroyEffect(GetLastCreatedEffectBJ())
        call RemoveGuardPosition(GetLastCreatedUnit())
        call GroupAddUnitSimple(GetLastCreatedUnit(), udg_G_Group)
        call IssuePointOrderLoc(GetLastCreatedUnit(), "attack", LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x9A060300))
        call TriggerSleepAction(1.00)
        call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
        set ydul_t=ydul_t + 1
    endloop
    call TriggerSleepAction(5.00)
    call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    set udg_G_Class=( ( udg_G_Class ) + ( 1 ) )
    call StartTimerBJ(udg_G_Timer, false, 120.00)
    call CreateTimerDialogBJ(GetLastCreatedTimerBJ(), ( "第" + ( I2S(udg_G_Class) + "即将来临" ) ))
    set udg_G_TimerFace=GetLastCreatedTimerDialogBJ()
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_G_Action takes nothing returns nothing
    set gg_trg_G_Action=CreateTrigger()
    call TriggerRegisterTimerExpireEvent(gg_trg_G_Action, udg_G_Timer)
    call TriggerAddAction(gg_trg_G_Action, function Trig_G_ActionActions)
endfunction
//===========================================================================
// Trigger: G_allattack_1
//===========================================================================
function Trig_G_allattack_1Conditions takes nothing returns boolean
    return ( ( IsUnitInGroup(GetTriggerUnit(), udg_G_Group) == true ) )
endfunction
function Trig_G_allattack_1Actions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRectCenter(gg_rct______________006________2))
    call IssuePointOrderLoc(GetTriggerUnit(), "attack", LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_G_allattack_1 takes nothing returns nothing
    set gg_trg_G_allattack_1=CreateTrigger()
    call YDWETriggerRegisterEnterRectSimpleNull(gg_trg_G_allattack_1 , gg_rct______________010)
    call YDWETriggerRegisterEnterRectSimpleNull(gg_trg_G_allattack_1 , gg_rct______________010_______u)
    call TriggerAddCondition(gg_trg_G_allattack_1, Condition(function Trig_G_allattack_1Conditions))
    call TriggerAddAction(gg_trg_G_allattack_1, function Trig_G_allattack_1Actions)
endfunction
//===========================================================================
// Trigger: G_allattack_2
//===========================================================================
function Trig_G_allattack_2Conditions takes nothing returns boolean
    return ( ( IsUnitInGroup(GetTriggerUnit(), udg_G_Group) == true ) )
endfunction
function Trig_G_allattack_2Actions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRectCenter(gg_rct______________000))
    call IssuePointOrderLoc(GetTriggerUnit(), "attack", LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_G_allattack_2 takes nothing returns nothing
    set gg_trg_G_allattack_2=CreateTrigger()
    call YDWETriggerRegisterEnterRectSimpleNull(gg_trg_G_allattack_2 , gg_rct______________006________2)
    call TriggerAddCondition(gg_trg_G_allattack_2, Condition(function Trig_G_allattack_2Conditions))
    call TriggerAddAction(gg_trg_G_allattack_2, function Trig_G_allattack_2Actions)
endfunction
//===========================================================================
// Trigger: G_victory
//===========================================================================
function Trig_G_victoryConditions takes nothing returns boolean
    return ( ( IsUnitInGroup(GetTriggerUnit(), udg_G_Group) == true ) )
endfunction
function Trig_G_victoryFunc002Func001A takes nothing returns nothing
    call CustomVictoryBJ(GetEnumPlayer(), true, true)
endfunction
function Trig_G_victoryActions takes nothing returns nothing
    call GroupRemoveUnitSimple(GetTriggerUnit(), udg_G_Group)
    if ( ( CountUnitsInGroup(udg_G_Group) == 0 ) and ( udg_G_Class >= 11 ) ) then
        call ForForce(udg_Player, function Trig_G_victoryFunc002Func001A)
    else
    endif
endfunction
//===========================================================================
function InitTrig_G_victory takes nothing returns nothing
    set gg_trg_G_victory=CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_G_victory, EVENT_PLAYER_UNIT_DEATH)
    call TriggerAddCondition(gg_trg_G_victory, Condition(function Trig_G_victoryConditions))
    call TriggerAddAction(gg_trg_G_victory, function Trig_G_victoryActions)
endfunction
//===========================================================================
// Trigger: Choosehero
//===========================================================================
function Trig_ChooseheroConditions takes nothing returns boolean
    return ( ( IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true ) and ( IsPlayerInForce(GetTriggerPlayer(), udg_Player) == false ) and ( GetOwningPlayer(GetTriggerUnit()) == Player(PLAYER_NEUTRAL_PASSIVE) ) )
endfunction
function Trig_ChooseheroActions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    if ( ( GetTriggerUnit() == udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())] ) ) then
        call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRandomLocInRect(gg_rct______________000))
        call SetUnitOwner(GetTriggerUnit(), GetTriggerPlayer(), true)
        call SetUnitPositionLoc(GetTriggerUnit(), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
        call PanCameraToTimedLocForPlayer(GetOwningPlayer(GetTriggerUnit()), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8), 0)
        call SelectUnitForPlayerSingle(GetTriggerUnit(), GetOwningPlayer(GetTriggerUnit()))
        call DisplayTextToForce(GetPlayersAll(), ( ( GetPlayerName(GetTriggerPlayer()) ) + ( "选择了" ) + ( GetUnitName(GetTriggerUnit()) ) ))
        call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
        call ForceAddPlayerSimple(GetTriggerPlayer(), udg_Player)
        call SetUnitManaPercentBJ(GetTriggerUnit(), 100)
    else
        set udg_Heros[GetConvertedPlayerId(GetTriggerPlayer())]=GetTriggerUnit()
        call DisplayTextToPlayer(GetTriggerPlayer(), 0, 0, ( "你确定要选择" + ( GetUnitName(GetTriggerUnit()) + "吗？" ) ))
    endif
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_Choosehero takes nothing returns nothing
    set gg_trg_Choosehero=CreateTrigger()
    call TriggerRegisterPlayerSelectionEventBJ(gg_trg_Choosehero, Player(0), true)
    call TriggerRegisterPlayerSelectionEventBJ(gg_trg_Choosehero, Player(1), true)
    call TriggerRegisterPlayerSelectionEventBJ(gg_trg_Choosehero, Player(2), true)
    call TriggerRegisterPlayerSelectionEventBJ(gg_trg_Choosehero, Player(3), true)
    call TriggerAddCondition(gg_trg_Choosehero, Condition(function Trig_ChooseheroConditions))
    call TriggerAddAction(gg_trg_Choosehero, function Trig_ChooseheroActions)
endfunction
//===========================================================================
// Trigger: RegetHero
//===========================================================================
function Trig_RegetHeroConditions takes nothing returns boolean
    return ( ( IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true ) and ( IsPlayerInForce(GetOwningPlayer(GetTriggerUnit()), udg_Player) == true ) )
endfunction
function Trig_RegetHeroFunc003T takes nothing returns nothing
    call SaveLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8, GetRectCenter(gg_rct______________000))
    call SetUnitManaPercentBJ(LoadUnitHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0xC303079D), 100)
    call ReviveHeroLoc(LoadUnitHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0xC303079D), LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8), true)
    call PanCameraToTimedLocForPlayer(GetOwningPlayer(LoadUnitHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0xC303079D)), LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8), 0)
    call SelectUnitForPlayerSingle(LoadUnitHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0xC303079D), GetOwningPlayer(LoadUnitHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0xC303079D)))
    call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8))
    call DestroyTimerDialog(LoadTimerDialogHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x9134E1DF))
    call FlushChildHashtable(YDLOC, GetHandleId(GetExpiredTimer()))
    call DestroyTimer(GetExpiredTimer())
endfunction
function Trig_RegetHeroActions takes nothing returns nothing
    local timer ydl_timer
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    call SaveTimerHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x312C4181, CreateTimer())
    call CreateTimerDialogBJ(LoadTimerHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x312C4181), ( GetUnitName(GetTriggerUnit()) + "复活剩余时间" ))
    set ydl_timer=LoadTimerHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x312C4181)
    call SaveUnitHandle(YDLOC, GetHandleId(ydl_timer), 0xC303079D, GetTriggerUnit())
    call SaveTimerDialogHandle(YDLOC, GetHandleId(ydl_timer), 0x9134E1DF, GetLastCreatedTimerDialogBJ())
    call SaveLocationHandle(YDLOC, GetHandleId(ydl_timer), 0x32A9E4C8, LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
    call TimerStart(ydl_timer, 10.00, false, function Trig_RegetHeroFunc003T)
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
    set ydl_timer=null
endfunction
//===========================================================================
function InitTrig_RegetHero takes nothing returns nothing
    set gg_trg_RegetHero=CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_RegetHero, EVENT_PLAYER_UNIT_DEATH)
    call TriggerAddCondition(gg_trg_RegetHero, Condition(function Trig_RegetHeroConditions))
    call TriggerAddAction(gg_trg_RegetHero, function Trig_RegetHeroActions)
endfunction
//===========================================================================
// Trigger: s1
//===========================================================================
function Trig_s1Conditions takes nothing returns boolean
    return ( ( IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true ) )
endfunction
function Trig_s1Actions takes nothing returns nothing
    local integer ydl_localvar_step= LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76)
 set ydl_localvar_step=ydl_localvar_step + 3
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xCFDE6C76, ydl_localvar_step)
 call SaveInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7, ydl_localvar_step)
    set bj_forLoopAIndex=1
    set bj_forLoopAIndexEnd=3
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        if ( ( GetItemTypeId(GetManipulatedItem()) == udg_S_wplx[bj_forLoopAIndex] ) ) then
            call SaveLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8, GetRectCenter(udg_S_jux[bj_forLoopAIndex]))
            call SetUnitPositionLoc(GetTriggerUnit(), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
            call PanCameraToTimedLocForPlayer(GetOwningPlayer(GetTriggerUnit()), LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8), 0)
            call SelectUnitForPlayerSingle(GetTriggerUnit(), GetOwningPlayer(GetTriggerUnit()))
            call AddSpecialEffectLocBJ(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8), "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.mdl")
            call DestroyEffect(GetLastCreatedEffectBJ())
            call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step, 0x32A9E4C8))
            call DoNothing()
 exitwhen true //(  )
        else
        endif
        set bj_forLoopAIndex=bj_forLoopAIndex + 1
    endloop
    call FlushChildHashtable(YDLOC, GetHandleId(GetTriggeringTrigger()) * ydl_localvar_step)
endfunction
//===========================================================================
function InitTrig_s1 takes nothing returns nothing
    set gg_trg_s1=CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_s1, EVENT_PLAYER_UNIT_PICKUP_ITEM)
    call TriggerAddCondition(gg_trg_s1, Condition(function Trig_s1Conditions))
    call TriggerAddAction(gg_trg_s1, function Trig_s1Actions)
endfunction
//===========================================================================
// Trigger: s2
//===========================================================================
function Trig_s2Actions takes nothing returns nothing
    if ( ( GetUnitTypeId(GetTriggerUnit()) == 'h002' ) ) then
        call AdjustPlayerStateBJ(30, GetOwningPlayer(GetKillingUnitBJ()), PLAYER_STATE_RESOURCE_GOLD)
    else
    endif
    if ( ( GetUnitTypeId(GetTriggerUnit()) == 'h003' ) ) then
        call AdjustPlayerStateBJ(20, GetOwningPlayer(GetKillingUnitBJ()), PLAYER_STATE_RESOURCE_LUMBER)
    else
    endif
    if ( ( GetUnitTypeId(GetTriggerUnit()) == 'h004' ) ) then
        call ModifyHeroStat(bj_HEROSTAT_STR, udg_Heros[GetConvertedPlayerId(GetOwningPlayer(GetKillingUnitBJ()))], bj_MODIFYMETHOD_ADD, 1)
        call ModifyHeroStat(bj_HEROSTAT_AGI, udg_Heros[GetConvertedPlayerId(GetOwningPlayer(GetKillingUnitBJ()))], bj_MODIFYMETHOD_ADD, 1)
        call ModifyHeroStat(bj_HEROSTAT_INT, udg_Heros[GetConvertedPlayerId(GetOwningPlayer(GetKillingUnitBJ()))], bj_MODIFYMETHOD_ADD, 1)
    else
    endif
endfunction
//===========================================================================
function InitTrig_s2 takes nothing returns nothing
    set gg_trg_s2=CreateTrigger()
    call TriggerRegisterAnyUnitEventBJ(gg_trg_s2, EVENT_PLAYER_UNIT_DEATH)
    call TriggerAddAction(gg_trg_s2, function Trig_s2Actions)
endfunction
//===========================================================================
// Trigger: s3
//===========================================================================
function Trig_s3Func002Func001Func001003002 takes nothing returns boolean
    return ( ( ( IsUnitAliveBJ(GetFilterUnit()) == true ) and ( GetOwningPlayer(GetFilterUnit()) == Player(5) ) ) )
endfunction
function Trig_s3Func002T takes nothing returns nothing
    set bj_forLoopAIndex=1
    set bj_forLoopAIndexEnd=3
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        call SaveGroupHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x214C62CC, YDWEGetUnitsInRectMatchingNull(udg_S_jux[bj_forLoopAIndex] , Condition(function Trig_s3Func002Func001Func001003002)))
        if ( ( CountUnitsInGroup(LoadGroupHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x214C62CC)) < 9 ) ) then
            call SaveLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8, GetRandomLocInRect(udg_S_jux[bj_forLoopAIndex]))
            call CreateNUnitsAtLoc(GetRandomInt(1, 5), udg_S_ut[bj_forLoopAIndex], Player(5), LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8), GetRandomDirectionDeg())
            call AddSpecialEffectLocBJ(LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8), "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.mdl")
            call DestroyEffect(GetLastCreatedEffectBJ())
            call RemoveLocation(LoadLocationHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x32A9E4C8))
        else
        endif
        call DestroyGroup(LoadGroupHandle(YDLOC, GetHandleId(GetExpiredTimer()), 0x214C62CC))
        set bj_forLoopAIndex=bj_forLoopAIndex + 1
    endloop
endfunction
function Trig_s3Actions takes nothing returns nothing
    local timer ydl_timer
    set ydl_timer=CreateTimer()
    call SaveGroupHandle(YDLOC, GetHandleId(ydl_timer), 0x214C62CC, LoadGroupHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7), 0x214C62CC))
    call SaveLocationHandle(YDLOC, GetHandleId(ydl_timer), 0x32A9E4C8, LoadLocationHandle(YDLOC, GetHandleId(GetTriggeringTrigger()) * LoadInteger(YDLOC, GetHandleId(GetTriggeringTrigger()), 0xECE825E7), 0x32A9E4C8))
    call TimerStart(ydl_timer, 1.00, true, function Trig_s3Func002T)
    call DestroyTrigger(GetTriggeringTrigger())
    set ydl_timer=null
endfunction
//===========================================================================
function InitTrig_s3 takes nothing returns nothing
    set gg_trg_s3=CreateTrigger()
    call TriggerRegisterTimerEventSingle(gg_trg_s3, 0.00)
    call TriggerAddAction(gg_trg_s3, function Trig_s3Actions)
endfunction
//===========================================================================
// Trigger: Chooseclass
//===========================================================================
function Trig_ChooseclassActions takes nothing returns nothing
    call SetUnitAbilityLevelSwapped('A001', gg_unit_n000_0024, GetRandomInt(1, 3))
endfunction
//===========================================================================
function InitTrig_Chooseclass takes nothing returns nothing
    set gg_trg_Chooseclass=CreateTrigger()
    call TriggerRegisterTimerEventSingle(gg_trg_Chooseclass, 5)
    call TriggerAddAction(gg_trg_Chooseclass, function Trig_ChooseclassActions)
endfunction
//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig__________u()
    call InitTrig_SetDate()
    call InitTrig_hg()
    call InitTrig_G_Action()
    call InitTrig_G_allattack_1()
    call InitTrig_G_allattack_2()
    call InitTrig_G_victory()
    call InitTrig_Choosehero()
    call InitTrig_RegetHero()
    call InitTrig_s1()
    call InitTrig_s2()
    call InitTrig_s3()
    call InitTrig_Chooseclass()
endfunction
//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute(gg_trg__________u)
endfunction
//***************************************************************************
//*
//*  Players
//*
//***************************************************************************
function InitCustomPlayerSlots takes nothing returns nothing
    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call ForcePlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0), true)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)
    // Player 1
    call SetPlayerStartLocation(Player(1), 1)
    call ForcePlayerStartLocation(Player(1), 1)
    call SetPlayerColor(Player(1), ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(1), true)
    call SetPlayerController(Player(1), MAP_CONTROL_USER)
    // Player 2
    call SetPlayerStartLocation(Player(2), 2)
    call ForcePlayerStartLocation(Player(2), 2)
    call SetPlayerColor(Player(2), ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(2), true)
    call SetPlayerController(Player(2), MAP_CONTROL_USER)
    // Player 3
    call SetPlayerStartLocation(Player(3), 3)
    call ForcePlayerStartLocation(Player(3), 3)
    call SetPlayerColor(Player(3), ConvertPlayerColor(3))
    call SetPlayerRacePreference(Player(3), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(3), true)
    call SetPlayerController(Player(3), MAP_CONTROL_USER)
    // Player 4
    call SetPlayerStartLocation(Player(4), 4)
    call ForcePlayerStartLocation(Player(4), 4)
    call SetPlayerColor(Player(4), ConvertPlayerColor(4))
    call SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(4), true)
    call SetPlayerController(Player(4), MAP_CONTROL_COMPUTER)
    // Player 5
    call SetPlayerStartLocation(Player(5), 5)
    call ForcePlayerStartLocation(Player(5), 5)
    call SetPlayerColor(Player(5), ConvertPlayerColor(5))
    call SetPlayerRacePreference(Player(5), RACE_PREF_ORC)
    call SetPlayerRaceSelectable(Player(5), true)
    call SetPlayerController(Player(5), MAP_CONTROL_COMPUTER)
endfunction
function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_015
    call SetPlayerTeam(Player(0), 0)
    call SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(1), 0)
    call SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(2), 0)
    call SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(3), 0)
    call SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(4), 0)
    call SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    // Force: TRIGSTR_016
    call SetPlayerTeam(Player(5), 1)
    call SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
endfunction
function InitAllyPriorities takes nothing returns nothing
    call SetStartLocPrioCount(0, 2)
    call SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(1, 2)
    call SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(2, 2)
    call SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(3, 3)
    call SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
endfunction
//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************
//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("LordaeronSummerDay")
    call SetAmbientNightSound("LordaeronSummerNight")
    call SetMapMusic("Music", true, 0)
    call CreateRegions()
    call CreateAllUnits()
    call InitBlizzard()

call ExecuteFunc("YDTriggerSaveLoadSystem___Init")

    call InitGlobals()
    call InitCustomTriggers()
    call ConditionalTriggerExecute(gg_trg__________u) // INLINED!!
endfunction
//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************
function config takes nothing returns nothing
    call SetMapName("防守图模版")
    call SetMapDescription("没有说明")
    call SetPlayers(6)
    call SetTeams(6)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    call DefineStartLocation(0, - 1536.0, - 3136.0)
    call DefineStartLocation(1, - 1536.0, - 3136.0)
    call DefineStartLocation(2, - 1536.0, - 3136.0)
    call DefineStartLocation(3, - 1472.0, 1408.0)
    call DefineStartLocation(4, - 1536.0, - 3136.0)
    call DefineStartLocation(5, - 1536.0, - 3136.0)
    // Player setup
    call InitCustomPlayerSlots()
    call InitCustomTeams()
    call InitAllyPriorities()
endfunction




//Struct method generated initializers/callers:

