<? xG_upgrade_luaObj={}
local slk = require 'slk'
obj=slk.upgrade.Rhme:new('XG_LUA_upgrade_1') 
	obj.Name='击杀第18波近战'
	obj.effect1=''
	obj.Tip=''
	obj.Ubertip=''
	obj.goldbase='0'
	obj.lumberbase='0'
	obj.timebase='0'
	obj.goldmod='0'
	obj.lumbermod='0'
	obj.timemod='0'
	obj.maxlevel='1'
table.insert(xG_upgrade_luaObj,obj)
obj=slk.upgrade.Rhme:new('XG_LUA_upgrade_2') 
	obj.Name='击杀第19波近战'
	obj.effect1=''
	obj.Tip=''
	obj.Ubertip=''
	obj.goldbase='0'
	obj.lumberbase='0'
	obj.timebase='0'
	obj.goldmod='0'
	obj.lumbermod='0'
	obj.timemod='0'
	obj.maxlevel='1'
table.insert(xG_upgrade_luaObj,obj)
?>