//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	index = 序号
	name = 名字
	describe = 提示说明
	stateFormula = 数值公式
	attribute = 属性附加
	targetType = 目标类型(无目标/点/单位/单位或点)
	 passive = 是否被动技能
	icon = 图标
	model = 模型
	range = 施放范围
	area = 影响区域
	manaCost = 魔法消耗
	hotKey = 快捷键
	maxCd = 冷却
	x = 按钮x
	y = 按钮y
	#<%1%># = 配置代码
*/
export type data_type = {
	id?: string
	class?: string
	index?: number
	name?: string
	describe?: string
	stateFormula?: any
	attribute?: any
	targetType?: string
	passive?: boolean
	icon?: string
	model?: string
	range?: number
	area?: number
	manaCost?: number
	hotKey?: string
	maxCd?: number
	x?: number
	y?: number
    [key:string]: any
}

declare global {
    type t_技能演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"群锤",
		"class":"技能",
		"index":0,
		"name":"群锤",
		"describe":"对范围内目标施放风暴之锤",
		"stateFormula":{
			"str":1
		},
		"targetType":"点",
		"passive":false,
		"icon":"ReplaceableTextures\\CommandButtons\\BTNStormBolt.blp",
		"model":"Abilities\\Spells\\Human\\StormBolt\\StormBoltMissile.mdl",
		"range":1000,
		"area":500,
		"manaCost":0,
		"hotKey":"Q",
		"maxCd":0,
		"x":0,
		"y":2
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	},
	{
		"manaCost":0
	}
]
export const d_技能演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
