//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	unique = 唯一
	attribute = 属性附加
	maxCd = 冷却时间
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: any
	lumberCost?: any
	pawnable?: any
	unique?: any
	attribute?: any
	maxCd?: any
    [key:string]: any
}

declare global {
    type t_物品演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"杀主刀",
		"class":"基础",
		"passive":true,
		"name":"|cffff0000杀主刀",
		"describe":"增加10点力量",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp"
	},
	{
		"id":"属性丹",
		"class":"基础",
		"passive":false,
		"name":"|cffff0001属性丹",
		"describe":"点击使用后获得10点全属性",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp"
	}
]
export const d_物品演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
